/// Defines opcodes for IRIS VM

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpCode {
    Constant     = 1,
    Nil          = 2,
    True         = 3,
    False        = 4,
    Pop          = 5,
    GetLocal     = 6,
    SetLocal     = 7,
    GetGlobal    = 8,
    DefineGlobal = 9,
    SetGlobal    = 10,
    GetProperty  = 11,
    SetProperty  = 12,
    NewInstance  = 13,
    Invoke       = 14,
    GetSuper     = 15,
    Equal        = 16,
    NotEqual     = 17,
    Greater      = 18,
    Less         = 19,
    Add          = 20,
    Sub          = 21,
    Mul          = 22,
    Div          = 23,
    Negate       = 24,
    Jump         = 25,
    JumpIfFalse  = 26,
    Loop         = 27,
    Call         = 28,
    Return       = 29,
    Throw        = 30,
    Try          = 31,
    EndTry       = 32,
    Print        = 33,
}
